feat: Text toolbar in macOS compose view
Infomaniak/ios-kMail pull request #1552
Opened 2024-09-23 15:12 UTC by lebojo

This feature adds text formatting options to the mail editor, allowing users to apply bold, italic, underline, text color, and font size. A new toolbar is introduced for easy access to these features on MacOS.

2024-09-25 07:13 UTC, valentinperignon reviewed
First review to fix first issues

2024-09-25 07:13 UTC, valentinperignon commented on Mail/Views/New Message/ComposeMessageMacosToolbarView.swift
> +                        )
You can use a trailing closure here

2024-09-25 07:13 UTC, valentinperignon commented on Mail/Views/New Message/ComposeMessageMacosToolbarView.swift
> +            .scaleEffect(configuration.isPressed ? 0.95 : 1.0)
We don't use the scaleEffect and won't introduce a new effect

2024-09-25 07:13 UTC, valentinperignon commented on Mail/Views/New Message/ComposeMessageMacosToolbarView.swift
> +                withAnimation(.easeInOut(duration: 0.25)) {
A default animation would be better here. So the animation depends on the environment

2024-09-25 07:13 UTC, valentinperignon commented on Mail/Views/New Message/ComposeMessageMacosToolbarView.swift
> +                        .scaleEffect(1.5)
Is it a good idea to use a scaleEffect here? Seems to be a hack.

2024-09-25 07:13 UTC, valentinperignon commented on Mail/Views/New Message/ComposeMessageMacosToolbarView.swift
> +                        .foregroundColor(.white)
We use MailTextStyle to give a color and font to a text.
Here, it is a body regular with #F5F5F

2024-09-25 07:13 UTC, valentinperignon commented on Mail/Views/New Message/ComposeMessageMacosToolbarView.swift
> +                        .padding()
We never use a padding without value

2024-10-07 13:23 UTC, PhilippeWeidmann commented on Mail/Views/New Message/ComposeMessageMacosToolbarViewModifier.swift
> +//
```suggestion

```

2024-10-07 13:24 UTC, PhilippeWeidmann commented on Mail/Views/New Message/ComposeMessageMacosToolbarView.swift
> +                        .buttonStyle(MacosToolbarButtonStyle(isActive: item.isSelected(textAttributes: textAttributes)))
Make a static style func so that it can be called like this `.buttonStyle(.macosToolbarButtonStyle(...))`

2024-10-07 13:31 UTC, PhilippeWeidmann commented on Mail/Views/New Message/ComposeMessageMacosToolbarView.swift
> +            .background(isActive ? accentColor.secondary.swiftUIColor : .clear)
Do not duplicate backgrounds. Create a computed property that returns the correct background

2024-10-08 06:25 UTC, valentinperignon requested changes
We also need to get the icons in 24x24 before merging

2024-10-08 06:25 UTC, valentinperignon commented on Mail/Views/New Message/ComposeMessageMacosToolbarView.swift
> +            .frame(maxWidth: .infinity, alignment: .leading)
The infinity frame isn't necessary

2024-10-08 06:25 UTC, valentinperignon commented on Mail/Views/New Message/ComposeMessageMacosToolbarView.swift
> +        VStack(spacing: 0) {
Add an alignment leading to the VStack

2024-10-08 06:25 UTC, valentinperignon commented on Mail/Views/New Message/ComposeMessageBodyView.swift
>          VStack {
We should refactor this view. Ask me, we will see together.

2024-10-08 06:25 UTC, valentinperignon commented on Mail/Views/New Message/ComposeEditor/ComposeEditor.swift
>      var body: some View {
We should add a VStack here. How are the 3 views spaced?

2024-10-08 08:22 UTC, lebojo commented on Mail/Views/New Message/ComposeEditor/EditorToolbar.swift
> +    case attachment
This is to match the figma

2024-10-09 07:51 UTC, valentinperignon commented on Mail/Views/New Message/ComposeEditor/EditorToolbarView.swift
> +            let actionImage = action.icon.image.resize(size: CGSize(width: 24, height: 24))
We don't need to use the resize function anymore

2024-10-09 07:51 UTC, valentinperignon commented on Mail/Views/New Message/ComposeMessageBodyView.swift
> +            ComposeMessageMacosToolbarView(
You can move this view in the same folder where is the iOS toolbar
You can also rename both toolbars, something like editorMobileToolbarView and editorDesktopToolbarView

2024-10-09 07:51 UTC, valentinperignon commented on Mail/Views/New Message/ComposeMessageMacosToolbarView.swift
> +                                .resizable()
Not necessary if you check what iConSize does

2024-10-09 07:51 UTC, valentinperignon commented on Mail/Views/New Message/ComposeMessageMacosToolbarView.swift
> +                            item.icon.swiftUIImage
The button doesn't have the correct color

2024-10-09 07:51 UTC, valentinperignon commented on Mail/Views/New Message/ComposeMessageMacosToolbarView.swift
> +                        Divider()
The divider does not have the correct color or height

2024-10-10 13:33 UTC, valentinperignon commented on Mail/Views/New Message/ComposeEditor/EditorDesktopToolbarView.swift
> +    @InjectService var featureFlagsManageable: FeatureFlagsManageable
```suggestion
    @InjectService private var featureFlagsManageable: FeatureFlagsManageable
```

2024-10-10 13:33 UTC, valentinperignon commented on Mail/Views/New Message/ComposeEditor/EditorDesktopToolbarView.swift
> +    var allItems: [[EditorToolbarAction]] {
```suggestion
    private var allItems: [[EditorToolbarAction]] {
```

2024-10-10 13:33 UTC, valentinperignon commented on Mail/Views/New Message/ComposeEditor/EditorDesktopToolbarView.swift
> +    var backgroundColor: Color {
```suggestion
    private var backgroundColor: Color {
```

2024-10-11 06:24 UTC, merged